"""State and memory models for LegalPilot-VN."""

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field


class EnterpriseProfile(BaseModel):
    """Corporate profile stored in enterprise SQLite memory."""

    id: int | None = None
    company_name: str
    entity_type: str = Field(
        ...,
        description="Business structure, e.g., TNHH (LLC), Cổ phần (JSC), Doanh nghiệp FDI",
    )
    charter_capital: float = Field(..., description="Charter capital in VND")
    sector_code: str = Field(..., description="VSIC sector code or description")
    headcount: int = Field(..., description="Total employees participating in social insurance")
    foreign_ownership_ratio: float = Field(
        default=0.0,
        description="Foreign equity ownership ratio from 0.0 to 1.0",
    )
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class AuditHistoryRecord(BaseModel):
    """Audit record stored in SQLite."""

    id: int | None = None
    session_id: str
    query: str
    compliance_matrix_path: str
    auditor_score: float
    human_token: str | None = None
    approved_at: datetime | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class StatuteCacheEntry(BaseModel):
    """Cached statutory validity record from vbpl.vn or gazette."""

    law_id: str
    document_number: str
    title: str
    effective_date: str
    status: str = Field(
        ...,
        description="Status: 'active', 'expired', 'partially_expired', or 'not_in_force'",
    )
    raw_metadata: dict[str, Any] = Field(default_factory=dict)
    cached_at: float = Field(default_factory=lambda: datetime.now(UTC).timestamp())
    ttl_seconds: int = 86400

    @property
    def is_expired(self) -> bool:
        """Checks if the cached entry has exceeded its TTL."""
        elapsed = datetime.now(UTC).timestamp() - self.cached_at
        return elapsed > self.ttl_seconds


class AtomicClaim(BaseModel):
    """An individual atomic proposition extracted from a compliance draft."""

    claim_id: str
    text: str
    cited_statute: str
    cited_article: str | None = None
    is_grounded: bool = False
    is_statute_active: bool = False
    auditor_notes: str | None = None


class AuditReport(BaseModel):
    """Report generated by the Claim Auditor Agent."""

    total_claims: int
    grounded_claims: int
    unsupported_claims: list[AtomicClaim] = Field(default_factory=list)
    grounding_rate: float
    is_fully_verified: bool
    critique_feedback: str | None = None


class LegalAgentState(BaseModel):
    """Shared execution state passed between agents in the orchestration loop."""

    session_id: str
    user_query: str
    case_facts: dict[str, Any] = Field(default_factory=dict)
    enterprise_profile: EnterpriseProfile | None = None
    plan_steps: list[str] = Field(default_factory=list)
    current_step: int = 0
    retrieved_clauses: list[dict[str, Any]] = Field(default_factory=list)
    validity_status: dict[str, str] = Field(default_factory=dict)
    candidate_draft: str | None = None
    audit_report: AuditReport | None = None
    retry_count: int = 0
    human_confirmation_needed: bool = False
    human_token: str | None = None
    final_dossier_path: str | None = None
    execution_trace: list[dict[str, Any]] = Field(default_factory=list)
